import = ["/home/maxrob/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"]

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Space"
mods = "Alt"

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true

[window.padding]
x = 5
y = 5
