[language-server.clangd]
command = "clangd"
args = ["--function-arg-placeholders"]

[[language]]
name = "cpp"
auto-format = true

roots = [".clang-format"]

[language-server.julia]
command = "julia"
args = ["--startup-file=no", 
        "--history-file=no",
        "--quiet", 
        "--sysimage=/home/maxrob/.config/helix/julialsp.so",
        "--sysimage-native-code=yes",
        "--quiet",
        "-e",
        """
                using LanguageServer;
                runserver();
        """,]
timeout = 60

[[language]]
name = "julia"
scope = "source.julia"
injection-regex = "julia"
file-types = ["jl"]
roots = []
comment-token = "#"

indent = { tab-width = 2, unit = "  " }

# latex stuff is not tested yet

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true
ForwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:1:%f", "%p"]

[[language]]
name = "latex"
auto-format = true
